apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: examcard-dev-server
  name: examcard-dev-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: examcard-dev-server
  template:
    metadata:
      labels:
        app: examcard-dev-server
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
            - name: LOG_URL
              value: http://couchdb-svc:5984
            - name: LOG_SOURCE
              value: examcard_dev
            - name: NEXTAUTH_URL_INTERNAL
              value: http://127.0.0.1:3000
            - name: NEXTAUTH_URL
              value: https://ecard-uat.tooieapp.com
            - name: NEXT_PUBLIC_ENV
              value: uat
            - name: IMAGE_API_SERVER
              value: http://exam-api:8080/v2
          image: >-
            ${IMAGE}
          imagePullPolicy: Always
          name: examcard-dev-server
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: acr-credential-c6c63a12436031a13361512e545490fd
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: volume-localtime
