import { Block, MultipleChoice, TextInput } from "../model/types";
import range from "lodash/range";
import { Exam } from "@prisma/client";

function createStudentIdArea(startY: number): Block[] {
  const blockSize = 6;
  const topRow = range(0, 4).map<TextInput>((i) => ({
    id: "id" + i,
    type: "textInput",
    x: 3 + i * (blockSize + 3),
    y: startY,
    height: blockSize + 1,
    width: blockSize + 1,
    border: { right: true, left: true, bottom: true, top: true },
  }));
  const mcList = range(0, 4).map<MultipleChoice>((i) => ({
    id: "mc" + i,
    type: "multipleChoice",
    x: i * (blockSize + 3) - 2,
    y: startY + 10,
    height: blockSize * 10,
    width: blockSize + 1,
    params: { direction: "column", size: 10, optionType: "number" },
  }));
  return [...topRow, ...mcList];
}

export function createTitle1(exam: Exam) {
  const cardTitle: Block = {
    id: "cardTitle",
    type: "area",
    border: { bottom: true },
    x: 0,
    y: 0,
    height: 10,
    width: 200,
    children: [
      {
        id: "examName",
        type: "textInput",
        x: 0,
        y: 0,
        height: 10,
        width: 200,
        title: `答题卡 【 ${exam.name} 】`,
        params: { fontSize: 18, justifyContent: true, alignItems: true },
      },
    ],
    params: { uuid: exam.uuid, qrcode: true, qrCodeSize: 25 },
  };
  const studentInfo: Block = {
    id: "studentInfo",
    type: "area",
    border: { bottom: true },
    x: 0,
    y: 10,
    height: 10,
    width: 160,
    children: [
      {
        id: "studentNameArea",
        type: "area",
        border: { right: true },
        x: 0,
        y: 0,
        height: 10,
        width: 80,
        children: [
          {
            id: "studentName",
            type: "textInput",
            x: 2,
            y: 0,
            height: 10,
            width: 80,
            title: "姓名",
            params: { fontSize: 14, alignItems: true },
          },
        ],
      },
      {
        id: "classNameArea",
        type: "area",
        x: 82,
        y: 0,
        height: 10,
        width: 78,
        children: [
          {
            id: "className",
            type: "textInput",
            x: 0,
            y: 0,
            height: 10,
            width: 77,
            title: "班级",
            params: { fontSize: 14, alignItems: true },
          },
        ],
      },
    ],
  };
  const examExample: Block = {
    id: "examExample1Area",
    type: "area",
    x: 0,
    y: 55,
    height: 10,
    width: 160,
    border: { bottom: true },
    children: [
      {
        id: "examExample1",
        type: "textInput",
        x: 2,
        y: 0,
        height: 10,
        width: 156,
        params: {
          image: "/exam/rule.png",
        },
      },
    ],
  };
  const teacherBlock1: Block = {
    id: "ifNot1",
    type: "area",
    x: 0,
    y: 0,
    height: 10,
    width: 40,
    children: [
      {
        id: "ifNot1Label",
        type: "textInput",
        x: 3,
        y: 2,
        height: 5,
        width: 15,
        title: "缺考：",
        params: { fontSize: 11 },
      },
      {
        id: "ifNot1Input",
        type: "textInput",
        x: 15,
        y: 2,
        height: 4,
        width: 7,
        border: { right: true, left: true, bottom: true, top: true },
      },
    ],
  };
  const teacherBlock2: Block = {
    id: "ifNot2",
    type: "area",
    x: 40,
    y: 0,
    height: 10,
    width: 40,
    children: [
      {
        id: "ifNot2Label",
        type: "textInput",
        x: 3,
        y: 2,
        height: 5,
        width: 15,
        title: "违纪：",
        params: { fontSize: 11 },
      },
      {
        id: "ifNot2Input",
        type: "textInput",
        x: 15,
        y: 2,
        height: 4,
        width: 7,
        border: { right: true, left: true, bottom: true, top: true },
      },
    ],
  };
  const teacherBlock3: Block = {
    id: "ifNot3",
    type: "area",
    x: 0,
    y: 6,
    height: 5,
    width: 160,
    children: [
      {
        id: "ifNot3Label",
        type: "textInput",
        x: 3,
        y: 2,
        height: 5,
        width: 158,
        title: "缺考、违纪标记考生禁涂 由监考老师填涂",
        params: { fontSize: 11 },
      },
    ],
  };
  const teacherBlock: Block = {
    id: "teacher1",
    type: "area",
    x: 0,
    y: 65,
    height: 10,
    width: 160,
    children: [teacherBlock1, teacherBlock2, teacherBlock3],
  };

  const children: Block[] = [
    cardTitle,
    studentInfo,
    {
      id: "examNot1",
      type: "area",
      x: 0,
      y: 20,
      height: 35,
      width: 160,
      border: { bottom: true },
      children: [
        {
          id: "examNotTitle1",
          type: "textInput",
          x: 2,
          y: 2,
          height: 6,
          width: 158,
          title: "注意事项",
          params: { fontSize: 12 },
        },
        {
          id: "examNote1",
          type: "textInput",
          x: 2,
          y: 10,
          height: 6,
          width: 158,
          title:
            "1. 考生务必在每张答题卡上用黑色签字笔将自己的姓名、班级、学号信息填写清楚；",
          params: { fontSize: 11 },
        },
        {
          id: "examNote2",
          type: "textInput",
          x: 2,
          y: 16,
          height: 6,
          width: 158,
          title: "2. 选择题必须使用2B铅笔填涂；非选择题要书写工整、字迹清楚；",
          params: { fontSize: 11 },
        },
        {
          id: "examNote3",
          type: "textInput",
          x: 2,
          y: 22,
          height: 6,
          width: 158,
          title: "3. 超出答题区域书写的答案无效；",
          params: { fontSize: 11 },
        },
        {
          id: "examNote4",
          type: "textInput",
          x: 2,
          y: 28,
          height: 6,
          width: 158,
          title: "4. 保持卡面清洁，不要折叠、不要弄破。",
          params: { fontSize: 11 },
        },
      ],
    },
    examExample,
    teacherBlock,
    {
      id: "SID1",
      type: "area",
      border: { left: true },
      x: 160,
      y: 10,
      height: 70,
      width: 40,
      children: [
        {
          id: "examNote2",
          type: "textInput",
          x: 2,
          y: 0,
          height: 10,
          width: 65,
          title: "学号",
          params: { fontSize: 14, alignItems: true },
        },
        ...createStudentIdArea(10),
      ],
    },
  ];

  const title: Block = {
    id: "titleType1",
    type: "area",
    x: 5,
    y: 8,
    height: 80,
    width: 200,
    border: { right: true, left: true, bottom: true, top: true },
    children: children,
  };
  return title;
}

export function createTitle2(exam: Exam) {
  const titleName = `${exam.name} 答题卡`;
  const cardTitle: Block = {
    id: "cardTitle2",
    type: "area",
    border: { bottom: true },
    x: 0,
    y: 0,
    height: 16,
    width: 200,
    children: [
      {
        id: "examTitle21",
        type: "textInput",
        x: 0,
        y: 0,
        height: 8,
        width: 200,
        title: "普通高等学校招生全国统一考试",
        params: { fontSize: 18, justifyContent: true, alignItems: true },
      },
      {
        id: "examTitle22",
        type: "textInput",
        x: 0,
        y: 8,
        height: 8,
        width: 200,
        title: titleName,
        params: { fontSize: 14, justifyContent: true, alignItems: true },
      },
    ],
    params: { uuid: exam.uuid, qrcode: true, qrCodeSize: 25 },
  };

  const teacherBlock: Block = {
    id: "teacher2",
    type: "area",
    border: { top: true },
    x: 125,
    y: 56,
    height: 28,
    width: 35,
    children: [
      {
        id: "teacherNotice21",
        type: "textInput",
        x: 0,
        y: 3,
        height: 6,
        width: 35,
        title: "缺考标记",
        params: { fontSize: 11, justifyContent: true },
      },
      {
        id: "teacherNotice22",
        type: "textInput",
        x: 0,
        y: 9,
        height: 6,
        width: 35,
        title: "考生禁涂",
        params: { fontSize: 11, justifyContent: true },
      },
      {
        id: "teacherNotice23",
        type: "textInput",
        x: 0,
        y: 15,
        height: 6,
        width: 35,
        title: "由监考员填涂",
        params: { fontSize: 11, justifyContent: true },
      },
      {
        id: "ifNot24",
        type: "textInput",
        x: 14,
        y: 21,
        height: 4,
        width: 7,
        border: { top: true, bottom: true, left: true, right: true },
      },
    ],
  };
  const children: Block[] = [
    cardTitle,
    {
      id: "studentName2Area",
      type: "area",
      border: { right: true },
      x: 0,
      y: 16,
      height: 10,
      width: 125,
      children: [
        {
          id: "studentName2",
          type: "textInput",
          x: 2,
          y: 0,
          height: 9,
          width: 123,
          title: "姓名",
          params: { fontSize: 14, alignItems: true },
        },
      ],
    },
    {
      id: "personID2Area",
      type: "area",
      x: 125,
      y: 16,
      height: 10,
      width: 35,
      children: [
        {
          id: "personID2",
          type: "textInput",
          x: 2,
          y: 0,
          height: 9,
          width: 33,
          title: "准考证号",
          params: { fontSize: 14, alignItems: true },
        },
      ],
    },
    {
      id: "zhengquetiantu2Area",
      type: "area",
      x: 125,
      y: 26,
      height: 15,
      width: 35,
      border: { top: true, bottom: true },
      children: [
        {
          id: "zhengquetiantu2",
          type: "textInput",
          x: 2,
          y: 0,
          height: 15,
          width: 33,
          params: {
            image: "/exam/correct-example.png",
          },
        },
      ],
    },
    {
      id: "cuowutiantu2Area",
      type: "area",
      x: 125,
      y: 41,
      height: 15,
      width: 35,
      children: [
        {
          id: "cuowutiantu2",
          type: "textInput",
          x: 2,
          y: 0,
          height: 15,
          width: 33,
          params: {
            image: "/exam/error-example.png",
          },
        },
      ],
    },
    teacherBlock,
    {
      id: "examNot2",
      type: "area",
      x: 0,
      y: 26,
      height: 58,
      width: 125,
      border: { top: true, right: true },
      children: [
        {
          id: "examNotLabel2",
          type: "textInput",
          x: 2,
          y: 2,
          height: 6,
          width: 123,
          title: "注意事项",
          params: { fontSize: 12 },
        },
        {
          id: "examNot12",
          type: "textInput",
          x: 2,
          y: 10,
          height: 6,
          width: 123,
          title:
            "1.答题前，考生须用0.5mm黑色字迹的签字笔在规定位置填写自己的姓名、",
          params: { fontSize: 11 },
        },
        {
          id: "examNot122",
          type: "textInput",
          x: 2,
          y: 16,
          height: 6,
          width: 123,
          title: "准考证号；",
          params: { fontSize: 11 },
        },
        {
          id: "examNot22",
          type: "textInput",
          x: 2,
          y: 22,
          height: 12,
          width: 123,
          title:
            "2.选择题必须使用2B铅笔填涂；非选择题必须使用0.5mm黑色字迹的签字笔书写，字体工整、笔迹清楚；",
          params: { fontSize: 11 },
        },
        {
          id: "examNot32",
          type: "textInput",
          x: 2,
          y: 34,
          height: 12,
          width: 123,
          title:
            "3.请按照题号顺序在各题目的答题区域内作答，超出答题区域书写的答案无效；在草稿纸、试题卷上答题无效；",
          params: { fontSize: 11 },
        },
        {
          id: "examNot42",
          type: "textInput",
          x: 2,
          y: 46,
          height: 6,
          width: 123,
          title: "4.保持卡面清洁，不要折叠、不要弄破；",
          params: { fontSize: 11 },
        },
        {
          id: "examNot52",
          type: "textInput",
          x: 2,
          y: 52,
          height: 7,
          width: 123,
          title: "5.考试结束，将本答题卡和试卷一并交回。",
          params: { fontSize: 11 },
        },
      ],
    },
    {
      id: "SID2",
      type: "area",
      x: 160,
      y: 16,
      height: 68,
      width: 40,
      border: { left: true },
      children: createStudentIdArea(3),
    },
  ];

  const title: Block = {
    id: "titleType2",
    type: "area",
    x: 5,
    y: 8,
    height: 84,
    width: 200,
    border: { right: true, left: true, bottom: true, top: true },
    children: children,
  };
  return title;
}
